version: '3.8'

services:
  mongodb-test:
    image: mongo:7
    container_name: mongodb-test
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=myapp_test
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    tmpfs:
      - /data/db
